services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  frontend:
    image: node:22
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env

  # バックエンドのbuildステージまでのPoetry操作用サービス
  backend-build:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: build
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file:
      - ./backend/.env
    entrypoint: ["/bin/bash"]
    tty: true
