[tool.poetry]
name = "aikon-backend"
version = "0.1.0"
description = "Aikon FastAPI backend"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.110"
uvicorn = "^0.29"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

