name: Deploy Backend to Cloud Run

on:
  push:
    tags:
      - 'v*'

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: aikon-backend
          image: asia-northeast1-docker.pkg.dev/aikon-461600/cloud-run-source-deploy/aikon-backend:${{ github.sha }}
          region: asia-northeast1
