name: Deploy Backend to Cloud Run
on:
  workflow_dispatch:
  repository_dispatch:
    types: [backend-cd]

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Show working directory before GCP auth
        run: |
          pwd
          ls -l

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Show working directory before docker config
        run: |
          pwd
          ls -l

      - name: Configure docker for Artifact Registry
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Show working directory before build & push
        run: |
          pwd
          ls -l

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: asia-northeast1-docker.pkg.dev/aikon-461600/cloud-run-source-deploy/aikon/aikon-backend:${{ github.sha }}

      - name: Show working directory before deploy-cloudrun
        run: |
          pwd
          ls -l

      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: aikon-backend
          image: asia-northeast1-docker.pkg.dev/aikon-461600/cloud-run-source-deploy/aikon/aikon-backend:${{ github.sha }}
          region: asia-northeast1

      - name: Show working directory before extract-issues
        run: |
          pwd
          ls -l

      - name: Extract issues from PR body
        id: extract-issues
        run: |
          ISSUES=$(echo '${{ github.event.pull_request.body }}' | grep -oE '#[0-9]+' | tr -d '#' | jq -R -s -c 'split("\n")[:-1]|map(tonumber)')
          echo "ISSUES=$ISSUES" >> $GITHUB_OUTPUT

  comment-issues:
    needs: [backend-deploy]
    if: needs.backend-deploy.outputs.ISSUES != '' && needs.backend-deploy.outputs.ISSUES != 'null'
    runs-on: ubuntu-latest
    steps:
      - name: Comment on issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUES: ${{ needs.backend-deploy.outputs.ISSUES }}
          REF: ${{ github.ref }}
        run: |
          for issue in $(echo "$ISSUES" | jq '.[]'); do
            gh issue comment "$issue" --body ":rocket: Backend has been successfully deployed to Cloud Run!（$REF）"
          done
        shell: bash