name: Deploy Backend to Cloud Run
on:
  push:
    tags:
      - 'v*'

jobs:
  backend-deploy:
    if: startsWith(github.ref, 'refs/tags/v') && github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    outputs:
      issues: ${{ steps.extract-issues.outputs.ISSUES }}
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure docker for Artifact Registry
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: asia-northeast1-docker.pkg.dev/aikon-461600/cloud-run-source-deploy/aikon/aikon-backend:${{ github.sha }}

      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: aikon-backend
          image: asia-northeast1-docker.pkg.dev/aikon-461600/cloud-run-source-deploy/aikon/aikon-backend:${{ github.sha }}
          region: asia-northeast1

      - name: Extract issues from PR body
        id: extract-issues
        run: |
          ISSUES=$(echo '${{ github.event.pull_request.body }}' | grep -oE '#[0-9]+' | tr -d '#' | jq -R -s -c 'split("\n")[:-1]|map(tonumber)')
          echo "ISSUES=$ISSUES" >> $GITHUB_OUTPUT

  comment-issues:
    needs: backend-deploy
    if: needs.backend-deploy.outputs.issues != '' && needs.backend-deploy.outputs.issues != 'null'
    runs-on: ubuntu-latest
    steps:
      - name: Comment on issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUES: ${{ needs.backend-deploy.outputs.issues }}
          REF: ${{ github.ref }}
        run: |
          for issue in $(echo "$ISSUES" | jq '.[]'); do
            gh issue comment "$issue" --body ":rocket: Backend has been successfully deployed to Cloud Run!（$REF）"
          done
        shell: bash

  release:
    needs: backend-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${github.ref_name#v}" \
              --generate-notes
